web.http.port=7080
web.http.path=/api
web.http.credentials.port=7081
web.http.credentials.path=/api/credentials
web.http.identity.port=7082
web.http.identity.path=/api/identity
web.http.did.port=7083
web.http.did.path=/
web.http.version.port=7085
web.http.version.path=/api/version
web.http.sts.port=7086
web.http.sts.path=/api/sts
edc.iam.did.web.use.https=false
edc.ih.api.superuser.key=c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo=
edc.mvd.credentials.path=assets/
edc.vault.hashicorp.url=http://localhost:8200
edc.vault.hashicorp.token=root
edc.datasource.default.url=jdbc:postgresql://localhost:5432/postgres
edc.datasource.default.user=postgres
edc.datasource.default.password=password
edc.sql.schema.autocreate=true